---
dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^1.1.0
  flutter:
    sdk: flutter
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.17.6 <3.0.0"
flutter:
  uses-material-design: true
name: xgrid_test_app
publish_to: none
version: 1.0.0+1
